### ISSUE TITLE
moq.github.io and moqthis.com redirect to landing site

### ISSUE THREAD

**Issue by mikemccaughan** [moq/moq.github.io#4]
Right now, going to https://moq.github.io/ redirects to `http://wwn.moqthis.com/`, where `n` is replaced by a number and shows a GoDaddy landing/holding page.

**Comment by mikemccaughan** [comment]
This appears to have been fixed for https://moq.github.io/, but https://moqthis.com/ or http://moqthis.com/ end up on a track.vcdc.com page, which shows `{"error":"Redirect interrupted. DC"}` in plain text.

**Comment by kzu** [comment]
Yep, I'm not paying for moqthis.com anymore so it expired and someone else took it. Not planning on getting it back for now.
